# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21dbe9d401c00e68dcd3697a458dab255837fbfbc26b570319afe1b93f369faa85911899b238a7e15877598bdec114c7aad0ffdcd0e955471b7bc175c30e93a1

test:
  secret_key_base: 177db907d65dcb34de999960f7563ec8772a2c456e8f1033dee8bc0704368177578a9115e7f190d073fa01f39e6b49d26c01e03a0550818b5ac328849b9597b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
